### ISSUE TITLE
Linux Foundation Pricing Options - Crossed numbers not really crossed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2015.fossasia.org#18]
![screenshot from 2015-01-30 14 25 45](https://cloud.githubusercontent.com/assets/1583873/5976255/08aef8b2-a88c-11e4-94dd-ad86f4b6d760.png)

**Comment by walterheck** [comment]
Hmm, it looked good on chrome. I'm not much of a developer, can someone
tell me how to fix?

**Comment by tradzik** [comment]
Hi,
I can't reproduce this bug. I don't see that on website.
