### ISSUE TITLE
Move Brett Gray to Saturday and Choon Ming Goh to Sunday on the DevOps track please

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2015.fossasia.org#24]

**Comment by walterheck** [comment]
Actually Choon Ming can't do Sunday, but the real reason I asked is that Brett specifically asked for a Saturday slot. Can we move someone else to Sunday so Brett can move to Saturday?

**Comment by mariobehling** [comment]
Ok, moved Brett to Brett to Saturday.
