### ISSUE TITLE
Lightbox images are missing from img Folder (close.png, loading.gif, prev.png, next.png) causing 404 error

### ISSUE THREAD

**Issue by Parbhat** [fossasia/2015.fossasia.org#26]
![console](https://cloud.githubusercontent.com/assets/4817493/6504233/04ae6cd6-c35b-11e4-807d-bb85e5bfee12.png)

**Comment by mariobehling** [comment]
Oh this is a bad thing. Could you help and just make some small alternatives, please?

**Comment by tradzik** [comment]
I gonna add these images from official lightbox repository.
