### ISSUE TITLE
Navigation and sidebar are broken

### ISSUE THREAD

**Issue by tradzik** [fossasia/2015.fossasia.org#27]
When I enter website I see:

![f1](https://cloud.githubusercontent.com/assets/3431139/6510410/217961ee-c366-11e4-9291-b0f6d9804537.JPG)

When I press the button to hide sidebar: 

![f2](https://cloud.githubusercontent.com/assets/3431139/6510411/217d824c-c366-11e4-90c5-adbba8e138e0.JPG)

Some of content is cut

**Comment by mariobehling** [comment]
Fixxed thanks. Website is very slow in Asia. Any ideas?

**Comment by Parbhat** [comment]
hello @mariobehling , the size of background image of Topics covered section is 305 KB. The image is being fetched from tumblr, I think size of image can be reduced significantly and stored on this repository. Image link - http://31.media.tumblr.com/d91942eddeeb832e44d7ac24196e0587/tumblr_n8gyrvGyzC1st5lhmo1_1280.jpg

**Comment by tradzik** [comment]
@Parbhat Hi, I agree with you, we can store it in our repo and this should speed-up our website a bit, however I have some doubts:
- it is JPG image, so there is no loseless compression available in this format (we'll be unable to make nice compression)
- I am not sure, we have license to store this image in our repo. IMO it is property of someone else; I do not really know  rules of tumblr, so I may be wrong, but we should ask orginal author for permission (?)

**Comment by Parbhat** [comment]
hello @ty221, I am also not sure about copyright of image. I had tried to compress the image and it is being compressed nicely with little effect on quality. So it will be good if we can get permission or change it with the other appropriate image.

**Comment by mariobehling** [comment]
@ty221 @Parbhat License is no issue. Please proceed with changing the image. On tumblr - this is a designer who we work with and you linked to his page here.

**Comment by Parbhat** [comment]
@mariobehling  thanks for clarification, I am changing it.

**Comment by Parbhat** [comment]
hello @mariobehling, the image is already changed :)

**Comment by tradzik** [comment]
As the navigation bug is fixed, we shouldn't make off-topic posts here. Closing...
