### ISSUE TITLE
Google.png seems a bit big for such a small logo - Find an alternative smaller image

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2015.fossasia.org#29]

**Comment by sudheesh001** [comment]
@mariobehling When the network is profiled, the image Google.png and RedHat.png almost have the same size after the gulp compression of the images, i.e. approx 19 - 23 KB, Can you describe more what you mean by `seems a bit big`, I'd love to fix this.

**Comment by tradzik** [comment]
How about this logo? Only 16 KB? http://codewiz.org/wiki/GoogleLogoAlpha.png

After conversion with OptiPng only 6 KB

**Comment by mariobehling** [comment]
great, please add it. thanks!
