### ISSUE TITLE
On the speakers.fossasia.org Google site, the bottom shows a "gadget section" - how to deactivate this section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2015.fossasia.org#35]
The goal is to "not show the gadget section". D
Did a quick Google search and no results. Maybe someone has time to find out how to do it.

**Comment by tradzik** [comment]
https://productforums.google.com/forum/#!topic/sites/HU8mkmfvGQM 

Article above may be helpful. Can't make bigger research, as I do not have access to control pages of this website.
