### ISSUE TITLE
Links displayed in "white" and therefore invisible in schedule section -> should be in Red

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2015.fossasia.org#36]
![screenshot from 2015-03-11 13 36 48](https://cloud.githubusercontent.com/assets/1583873/6590950/d27be412-c7f3-11e4-8a4e-a7450ccc36ac.png)
Correct red color code is: #e12b00

**Comment by mariobehling** [comment]
![screenshot from 2015-03-11 14 01 02](https://cloud.githubusercontent.com/assets/1583873/6591216/45a4ca8c-c7f7-11e4-86e3-62b3eb8c94b6.png)
Should look something like that.

**Comment by creativepsyco** [comment]
@joerx ha ha!

**Comment by creativepsyco** [comment]
I shall close mine

**Comment by joerx** [comment]
Sorry. Mario asked me, just did.

**Comment by creativepsyco** [comment]
@joerx cool yours is better.
