### ISSUE TITLE
Speakers Profile Social Links Missing and Misplaced

### ISSUE THREAD

**Issue by NaviRocker** [fossasia/2015.fossasia.org#49]
Andreas Bräu (Germany)  - https://www.linkedin.com/in/andreasbraeu/
Eugene Teo - https://twitter.com/eugeneteo
Jonathan "Duke" Leto - https://www.linkedin.com/in/jaleto/
Jan Jongboom (The Netherlands) - https://www.linkedin.com/in/jan-jongboom/
Bernd Erk - https://twitter.com/gethash
Prashant Kiran (India) - https://twitter.com/prasht63
Vipul Hari - https://www.linkedin.com/in/vipul-hari-884a76127/
Heena Mahour - https://www.linkedin.com/in/heena-mahour-a183ba99/

I added all the 8 links newly. Some didn't have a Link ad some were wrong links.
These are the Correct Links for the Speakers

**Comment by 0x48piraj** [comment]
@naveentherocker You should always put a **Fixes : #IssueNumber** to reference the corresponding issue :wink:

**Comment by 0x48piraj** [comment]
Also @naveentherocker , I saw your PR got merged. So, this issue is irrelevant now.
You can close this too :+1:
