### ISSUE TITLE
Adding Social Links

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/2015.fossasia.org#53]
Adding social links to speakers of FOSSASIA summit 2015,

**Comment by saarthakchats** [comment]
Adding:-

- Lennart Poettering - github.com/poettering
- https://www.facebook.com/pages/Lennart-Poettering/154561584591868
- Vivian Balakrishnan - https://www.facebook.com/Vivian.Balakrishnan.Sg/
- Stefan Koehler - https://twitter.com/oraclesk?lang=en
- Emily Chen - https://twitter.com/echenty?lang=en
- Sean Cross - https://www.linkedin.com/in/seancross
- https://github.com/veerappan
- Ricky Setyawan - https://twitter.com/dbmsboy

**Comment by nzec** [comment]
On it! (The ones which are not added yet)

**Comment by YashKumarVerma** [comment]
@mariobehling there are sill many speakers whose links are not added. still, issue closed ?

**Comment by YashKumarVerma** [comment]
adding :
-sudheesh001 - Sudheesh Singanamalla
-vivianbalakrishnan - Vivian Balakrishnan
-byte - Colin Charles
-kushaldas - Kushal Das
-julienlavergne - Julien Lavergne
-bproffitt - Brian Proffitt
-rolandturner-Roland Turner
-janjongboom- Jan Jongboom 

https://github.com/sudheesh001
https://github.com/vivianbalakrishnan
https://github.com/byte
https://github.com/kushaldas
https://github.com/julienlavergne
https://github.com/bproffitt
https://github.com/rolandturner
https://github.com/janjongboom
