### ISSUE TITLE
Unused video tag should be removed (has empty sources)

### ISSUE THREAD

**Issue by tradzik** [fossasia/2015.fossasia.org#9]
``` html
<div class="video-wrapper">
                        <video autoplay="" muted="" loop="">
                            <source src="" type="video/webm">
                            <source src="" type="video/mp4">
                            <source src="" type="video/ogg">    
                        </video>
</div>
```

**Comment by tradzik** [comment]
@mariobehling Can you explain me, why did you revert my commit there: https://github.com/fossasia/fossasia15/commit/1169a48d4b562e2ead207b746c3ade6c69e25889

**Comment by mariobehling** [comment]
This page is build with a premade paid theme template. New versions are generated from the original template. Apparently there are some bugs, which need to be fixed by the developers/designers. Maybe the 2015 site is not the best site to commit at the moment. Thanks

**Comment by tradzik** [comment]
@mariobehling Ok, understand! Thanks

**Comment by tradzik** [comment]
@mariobehling Can I help you in any way with foss.vn zuendbuch or any other repos? I know how to create websites and merge them. I think I may be helpful

**Comment by mariobehling** [comment]
My main goal is to move away from CMS. So to get the FOSSASIA sites 2010 and 2012 onto github is a priority. Don't know if you are interested in this.

**Comment by tradzik** [comment]
@mariobehling Yes I am. I want to help in that. However, I don't understand some issues (like e.g. about  gradient) and can't fix them. If you need my help please ping me
